day 4/MVC - View_Controller__Communication/Models/ErrorViewModel.cs
namespace MVC___View_Controller__Communication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

day 4/MVC - View_Controller__Communication/Models/Products.cs
namespace MVC___View_Controller__Communication.Models
{
    public class Products
    {
        public int pId { get; set; }
        public string pName { get; set; }
        public string pCategory { get; set; }
        public double pPrice { get; set; }
        public bool pIsInStock { get; set; }

        static List<Products> pList = new List<Products>()
        {
            new Products(){ pId=101, pName="Pepsi", pCategory="Cold-Drink", pIsInStock=true, pPrice=50},
            new Products(){ pId=102, pName="IPhone", pCategory="Electronics", pIsInStock=false, pPrice=150000},
        };

        public List<Products> GetAllProducts()
        {
            return pList;
        }

        public string AddProduct(Products newProduct)
        {
            //you can do validation of values coming from user and throw exception if value is not as per requirement
            //you can also push the value back to database
            pList.Add(newProduct);
            return "Product Added Successfully";
        }
    }
}

day 4/MVC - View_Controller__Communication/Controllers/CalculationController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC___View_Controller__Communication.Controllers
{
    public class CalculationController : Controller
    {

        [HttpGet] //this is by default and u do not need to set this
        public IActionResult Greetings()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Greetings(string txtguestName)
        {
            ViewBag.message = "Hello and Welcome to MVC " + txtguestName;
            return View();
        }

        [HttpGet]
        public IActionResult Calculate()
        {
            ViewBag.errMessage = "";
            return View();
        }

        [HttpPost]
        public IActionResult Calculate(int firstNum, int secondNum)
        {

            if (firstNum == 0 || secondNum == 0)
            {
                ViewBag.errMessage = "Please Enter Only Positive Numbers";
            }
            else if (firstNum < secondNum)
            {
                ViewBag.errMessage = "This will result in negative value";
            }
            else if (secondNum == 0)
            {
                ViewBag.errMessage = "We cannot divide a number with 0, this please put the second number greater than 1";
            }
            else
            {
                ViewBag.addition = firstNum + secondNum;
                ViewBag.subtraction = firstNum - secondNum;
                ViewBag.division = firstNum / secondNum;
                ViewBag.multiplication = firstNum * secondNum;
            }
            return View();
        }



        public IActionResult Index()
        {
            return View();
        }
    }
}

day 4/MVC - View_Controller__Communication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC___View_Controller__Communication.Models;
using System.Diagnostics;

namespace MVC___View_Controller__Communication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

day 4/MVC - View_Controller__Communication/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using MVC___View_Controller__Communication.Models;
namespace MVC___View_Controller__Communication.Controllers
{
    public class ProductsController : Controller
    {

        Products pobj = new Products();
        public IActionResult ShowProducts()
        {

            return View(pobj.GetAllProducts());
        }



        [HttpPost]
        public IActionResult ShowProducts(Products newProduct)
        {
            pobj.AddProduct(newProduct);
            return View(pobj.GetAllProducts());
        }
    }
}

day 4/MVC - View_Controller__Communication/Views/Calculation/Calculate.cshtml
<form method="POST">
    <input type="number" placeholder="Enter First Postive Number" name="firstNum" class="form-control"/>
    <input type="number" placeholder="Enter Second Postive Number" name="secondNum" class="form-control"/>

    <button class="btn btn-success">Calculate</button>

</form>


@if(ViewBag.errMessage != "")
{
    <h3 style="color:red"> @ViewBag.errMessage</h3>
}
else
{
<div>
    <h3> Addition : @ViewBag.addition </h3>
    <h3> Subtraction : @ViewBag.subtraction </h3>
    <h3> Division : @ViewBag.division </h3>
    <h3> Multiplication : @ViewBag.multiplication </h3>
</div>
}

day 4/MVC - View_Controller__Communication/Views/Calculation/Greetings.cshtml
<h1> Welcome to My Site </h1>



<form method="POST">
    <input type="text" placeholder="Please Enter Your Name" name="txtguestName"/>
    <button class="btn btn-primary"> Greet </button>
</form>

<h2> @ViewBag.message </h2>

day 4/MVC - View_Controller__Communication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

day 4/MVC - View_Controller__Communication/Views/Products/ShowProducts.cshtml
@model IEnumerable<MVC___View_Controller__Communication.Models.Products>

@{
    ViewData["Title"] = "ShowProducts";
}

<h1>ShowProducts</h1>

<form method="POST">
    <input type="number" placeholder="Product Id" name="newProduct.pId"  class="form-control"/>
    <input type="text" placeholder="Product Name" name="newProduct.pName"  class="form-control"/>
    <select name="newProduct.pCategory"  class="form-control">
        <option>Cold-Drink</option>
        <option>Electronics</option>
        <option>Shoes</option>
        <option>Cloths</option>
    </select>
    <input type="number" placeholder="Product Price" name="newProduct.pPrice"  class="form-control"/>
    <input type="text" placeholder="Product Is In Stock" name="newProduct.pIsInStock"  class="form-control"/>

    <button class="btn btn-primary"> Add Product</button>
</form>





<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.pId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pIsInStock)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.pId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pCategory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pIsInStock)
            </td>
          
        </tr>
}
    </tbody>
</table>

day 4/MVC - View_Controller__Communication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC___View_Controller__Communication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC___View_Controller__Communication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Shopping </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculation" asp-action="Greetings">Greetings</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculation" asp-action="Calculate">Calculations</a>
                        </li>

                        
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="ShowProducts">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC___View_Controller__Communication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>